### ISSUE TITLE
VS channels of RT to RT messages under a BC are not updated

### ISSUE THREAD

**Issue by diegoballencantor** [ni/niveristand-ballard-milStd1553-custom-device#202]
**Describe the bug**
I simulated a BC in the CH0 Core0 and 2 RTs in the CH1 Core0 of a Ballard card. I modified the Hardware file example (check the Files.zip file) you provided for an internal loopback.

The VS channels of a RT to RT message under the BC section are not updated according to the data of the transmitting RT. They show constantly the value 0. This issue is not observed if the BC and RT are defined in the same channel.

**To Reproduce**
1. Generate a scripted SDF with the provided scripting VI (check the Files.zip file).
2.Deploy the SDF in a VS project.
2. Check the VS channels of a RT to RT message under the BC section.

**Expected behavior**
The VS channels of the RT to RT channel should be updated according to the data of the transmitting RT.
![grafik](https://user-images.githubusercontent.com/43212279/143436619-bbc5e7ec-38eb-4bf6-acd1-167ad45294d3.png)

Current Behaviour
![grafik](https://user-images.githubusercontent.com/43212279/143436687-76ad82fc-2254-435c-ae4d-e3d27b1a508d.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux 64]

**Additional context*
[Files.zip](https://github.com/ni/niveristand-ballard-milStd1553-custom-device/files/7602674/Files.zip)
*

**Comment by dbendele** [comment]
@diegoballencantor 

With PR #204 that Karl just merged, I wanted to let you know that we ran the automated tests and specifically tested with multiple channels/cores of single-function hardware. 

In both RT to RT messages, we verified that the bus controller received the same data received by the Rx remote terminal.
![image](https://user-images.githubusercontent.com/25972098/144097537-7a8681e7-008d-451f-959e-1334b8bb5276.png)

I invite you to pull down the latest commits and test with more of your use cases. Thanks for filing this issue, and please continue filing issues and feature requests on the repo!
