### ISSUE TITLE
use a different value than 0 for terminalAddress element in the parameter XML file to identify BusController

### ISSUE THREAD

**Issue by fmussi** [ni/niveristand-ballard-milStd1553-custom-device#225]
The [parameter xml file](https://github.com/ni/niveristand-ballard-milStd1553-custom-device/blob/main/Docs/Parameters%20XML%20File/Parameters%20XML%20File.md) uses a remoteTerminal value of 0 to identify the Bus Controller.

There could be configurations where terminalAddress 0 has to be associated to a specific Remote Terminal. I would suggest to use a different value for the BC in the XML parameter file, that stays outside the range defined by the [1553 protocol](https://en.wikipedia.org/wiki/MIL-STD-1553#The_Remote_Terminal), e.g. -1 or 32

**Comment by bariskarkar** [comment]
I need to simulate RT0. Can you solve the problem?

**Comment by papowerNI** [comment]
@bariskarkar @fmussi 
We are working on adding this to the 1553 custom device currently, does the following revised parameter file make sense to you?  A false <simulate> would exclude the bus controller, and the additional property allows us to free up RT0 for use.

```
?xml version="1.0"?>
<parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<version>1.1</version>
	<channel>
		<hardwareChannel>0</hardwareChannel>
		<busController>
			<simulate>True</simulate>
			<name>MyBusController</name> (optional)
		</busController>
		<terminals>
			<terminal>
				<terminalAddress>0</terminalAddress>
			</terminal>
			<terminal>
				<terminalAddress>1</terminalAddress>
			</terminal>
			<terminal>
				<terminalAddress>15</terminalAddress>
			</terminal>
		</terminals>
```

**Comment by bariskarkar** [comment]
I think it makes sense. Thus, as in the protocol, we do not need to assign any terminal addresses for the BC.

**Comment by bariskarkar** [comment]
Hello papowner, thank you for your support. The documents have been updated but no release has been published yet. This causes differences between the current version of the documents and the last release. Can you publish a new release with the updated version?

**Comment by Karl-G1** [comment]
@bariskarkar We are finishing testing on the changes @papowerNI made over the last few weeks, then we will post a release tag with packaged builds. Should be soon.

**Comment by Karl-G1** [comment]
@bariskarkar [Release 23.3](https://github.com/ni/niveristand-ballard-milStd1553-custom-device/releases/tag/v23.3.0) was just posted with fixes added and documented over the last couple of weeks.
